
DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;

DROP TABLE ANSWERBOARD;

CREATE SEQUENCE BOARDNOSEQ;
CREATE SEQUENCE GROUPNOSEQ;

-- 글번호, 그룹번호, 그룹순서, 제목공백, 삭제여부(Y,N), 제목, 내용, 작성자, 작성일
CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSEQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	DELFLAG VARCHAR2(2) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(200) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT ANSWER_CK_DELFLAG CHECK (DELFLAG IN ('Y','N'))
);

-- 1번글 작성
INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	GROUPNOSEQ.NEXTVAL,
	1,
	0,
	'N',
	'제목입니다',
	'내용입니다',
	'작성자이다',
	SYSDATE
);

SELECT BOARDNO, GROUPNO, GROUPSEQ, TITLETAB, DELFLAG, TITLE, CONTENT, WRITER, REGDATE
FROM ANSWERBOARD
ORDER BY GROUPNO DESC, GROUPSEQ;

UPDATE ANSWERBOARD SET DELFLAG ='Y' WHERE BOARDNO = 1;


